name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
     - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    # - name: commit 
      # uses: actions/checkout@v4
    # - name: push
      # run: docker push <repo-name>:latest
